import Head from 'next/head'

import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar'
import Filters from '@/components/Filters'
import Items from '@/components/Items'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <Navbar />
        <Filters />
        <Items />
      </main>
    </>
  )
}
